# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c40380e2d30df121167115f76170c9b3e73c146d669ca89b3f3d0008b62935ec9227bbc50fd3c542b855dd53b61944bca69c6edaf48c795b927a11edeb0a2256

test:
  secret_key_base: 382fd70a08adf3b218cdfa669d7a9a7fe0c870f964caf363b85c6d0e8b7970a05fca733901e4ecf3bce69bf74173f02c7f43dcc3e09656fe402e5d1da53fca26

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
